---
- name: "set waagent.conf values for Provisioning.Enabled"
  replace:
    path: /etc/waagent.conf
    regexp: 'Provisioning\.Enabled=y'
    replace: 'Provisioning.Enabled=n'

- name: "set waagent.conf values for Provisioning.UseCloudInit"
  replace:
    path: /etc/waagent.conf
    regexp: 'Provisioning\.UseCloudInit=n'
    replace: 'Provisioning.UseCloudInit=y'

- name: "set waagent.conf values for ResourceDisk.Format"
  replace:
    path: /etc/waagent.conf
    regexp: 'ResourceDisk\.Format=y'
    replace: 'ResourceDisk.Format=n'

- name: "set waagent.conf values for ResourceDisk.EnableSwap"
  replace:
    path: /etc/waagent.conf
    regexp: 'ResourceDisk\.EnableSwap=y'
    replace: 'ResourceDisk.EnableSwap=n'

- name: "create /etc/cloud/cloud.cfg.d/91-azure_datasource.cfg"
  copy:
    content: "datasource_list: [ Azure ]"
    dest: /etc/cloud/cloud.cfg.d/91-azure_datasource.cfg
    backup: yes


- name: call to waagent to deprovision vm
  shell: sleep 2 && /usr/sbin/waagent -deprovision+user -force
  async: 1
  poll: 0
  ignore_errors: True
  register: deprov_output
  delegate_to: "{{ openshift_azure_vm_host }}"
  remote_user: "{{ openshift_azure_vm_admin_username }}"
  become: True
# taken from tests in https://github.com/ansible/ansible/pull/32589/files
# not sure if this is completely necessary but initial attempts
# errored because VM was not generalized and this seems to work around it.
- name: Deallocate the virtual machine
  azure_rm_virtualmachine:
    resource_group: "{{ openshift_azure_resource_group_name }}"
    name: "{{ openshift_azure_vm_name }}"
    allocated: no
    vm_size: "{{ openshift_azure_vm_size }}"

# generalize vm
- name: generalize the vm
  command: "az vm generalize --resource-group {{ openshift_azure_resource_group_name }} --name {{ openshift_azure_vm_name }}"
  register: gen_output

#- name: generalize the vm
#  azure_rm_virtualmachine:
#      resource_group: "{{ openshift_azure_resource_group_name }}"
#      name: "{{ openshift_azure_vm_name }}"
#      vm_size: "{{ openshift_azure_vm_size }}"

- name: Create an image from VM
  azure_rm_image:
    resource_group: "{{ openshift_azure_resource_group_name }}"
    source: "{{ openshift_azure_vm_name }}"
    name: "{{ openshift_azure_image_name }}-{{ ansible_date_time.epoch }}"
    os_type: Linux
    #source: "https://{{ openshift_azure_storage_account_name }}.blob.core.windows.net/{{ openshift_azure_vm_name }}/{{ openshift_azure_vm_name }}.vhd"
